name: deploy theme
on:
  push:
    branches: [ master ]

jobs:
  deploy:

    name: deploy theme
    runs-on: ubuntu-latest

    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            git fetch --all
            git reset --hard origin/master
